name: IPTV Otomatik Guncelleme

on:
  workflow_dispatch: # Elle çalıştırmak için buton açar
  schedule:
    # Her Çarşamba ve Cuma günü TSİ 16:00'da (UTC 13:00) çalışır
    - cron: '0 13 * * 3,5'

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Kodlari Cek
        uses: actions/checkout@v3

      - name: Python Hazirla
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Gerekli Paketleri Kur
        run: pip install requests

      - name: Botu Calistir
        run: python bot.py

      - name: Degisiklikleri Commit Et ve Pushla
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add liste.m3u
          git commit -m "Update IPTV list: $(date)" || echo "Degisiklik yok."
          git push
